# Generated by Django 4.1 on 2022-08-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='name',
        ),
    ]
